import javax.swing.*;
import java.awt.*;

public class ColorEditor
{
	public static void main( String[] args )
	{
		new ColorEditor().show();
	}

	void show()
	{
		frame = new JFrame( "Color Editor" );
		frame.setContentPane( framePanel );
		ImageIcon icon = new ImageIcon( getClass().getResource( "/SmallJIcon.png" ) );
		frame.setIconImage( icon.getImage() );
		frame.pack();
		frame.setLocationRelativeTo( null );
		frame.setVisible( true );
	}

	JFrame frame;
	JPanel framePanel;
	JTextField textField;
	JButton selectButton;
	JLabel imageLabel;
	JScrollBar redScrollBar;
	JScrollBar greenScrollBar;
	JScrollBar blueScrollBar;
	JPanel scrollBarsPane;

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$()
	{
		framePanel = new JPanel();
		framePanel.setLayout( new BorderLayout( 0, 0 ) );
		textField = new JTextField();
		textField.setText( "Color[ 0, 0, 200 ]" );
		framePanel.add( textField, BorderLayout.NORTH );
		selectButton = new JButton();
		selectButton.setText( "Select" );
		framePanel.add( selectButton, BorderLayout.SOUTH );
		imageLabel = new JLabel();
		imageLabel.setHorizontalAlignment( 0 );
		imageLabel.setIcon( new ImageIcon( getClass().getResource( "/Blue.png" ) ) );
		imageLabel.setText( "" );
		framePanel.add( imageLabel, BorderLayout.CENTER );
		scrollBarsPane = new JPanel();
		scrollBarsPane.setLayout( new GridBagLayout() );
		framePanel.add( scrollBarsPane, BorderLayout.WEST );
		redScrollBar = new JScrollBar();
		redScrollBar.setMaximum( 265 );
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.VERTICAL;
		scrollBarsPane.add( redScrollBar, gbc );
		greenScrollBar = new JScrollBar();
		greenScrollBar.setMaximum( 265 );
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.VERTICAL;
		scrollBarsPane.add( greenScrollBar, gbc );
		blueScrollBar = new JScrollBar();
		blueScrollBar.setMaximum( 265 );
		blueScrollBar.setValue( 200 );
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 0;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.VERTICAL;
		scrollBarsPane.add( blueScrollBar, gbc );
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$()
	{
		return framePanel;
	}

}
