import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class ImageEditor
{
	public static void main( String[] args )
	{
		new ImageEditor().show();
	}

	void show()
	{
		frame = new JFrame( "Image Editor" );
		frame.setContentPane( framePanel );
		ImageIcon icon = new ImageIcon( getClass().getResource( "/SmallJIcon.png" ) );
		frame.setIconImage( icon.getImage() );
		frame.pack();
		frame.setLocationRelativeTo( null );
		frame.setVisible( true );
	}

	JFrame frame;
	JPanel framePanel;
	JPanel colorPanel;
	JLabel imageLabel;
	JButton closeButton;
	JButton colorButton;
	JTextField colorTextField;
	private JScrollPane imageScrollPane;

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$()
	{
		framePanel = new JPanel();
		framePanel.setLayout( new BorderLayout( 0, 4 ) );
		framePanel.setBorder( BorderFactory.createTitledBorder( BorderFactory.createEmptyBorder( 4, 4, 4, 4 ), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null ) );
		colorPanel = new JPanel();
		colorPanel.setLayout( new BorderLayout( 4, 0 ) );
		framePanel.add( colorPanel, BorderLayout.NORTH );
		colorButton = new JButton();
		colorButton.setText( "Color" );
		colorPanel.add( colorButton, BorderLayout.WEST );
		colorTextField = new JTextField();
		colorTextField.setText( "Color[ 0, 0, 200 ]" );
		colorPanel.add( colorTextField, BorderLayout.CENTER );
		closeButton = new JButton();
		closeButton.setText( "Close" );
		framePanel.add( closeButton, BorderLayout.SOUTH );
		imageScrollPane = new JScrollPane();
		framePanel.add( imageScrollPane, BorderLayout.CENTER );
		imageLabel = new JLabel();
		imageLabel.setHorizontalAlignment( 0 );
		imageLabel.setIcon( new ImageIcon( getClass().getResource( "/SmallJIcon.png" ) ) );
		imageLabel.setText( "" );
		imageScrollPane.setViewportView( imageLabel );
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$()
	{
		return framePanel;
	}

}
